### ISSUE TITLE
Dont require mercury

### ISSUE THREAD

**Issue by kumavis** [twilson63/mercury-router#1]
you are only using `vdom` and `mercury.value`. No point in being modular if we pull in the whole thing.

you should require those two directly instead of the whole mercury package.
be sure to match the `vdom` version, as there are breaking changes.

**Comment by twilson63** [comment]
Done

**Comment by kumavis** [comment]
Nice! I tried using this last night _before_ the changes, and the click event handlers never fired for me. not sure why. replacing the `clickEvent` with my own handler worked.

**Comment by twilson63** [comment]
Cool,

I will check it out, did the example work out of the box?

Thanks

Tom

On Thu, Feb 5, 2015 at 2:22 PM, aaron notifications@github.com wrote:

> Nice! I tried using this last night before the changes, and the click
> event handlers never fired for me. not sure why. replacing the clickEvent
> with my own handler worked.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/twilson63/mercury-router/issues/1#issuecomment-73108889
> .

## 

Tom Wilson
Jack Russell Software Company Division of CareKinesis
494 Wando Park Blvd
Mount Pleasant, SC  29464
Phone: 843-606-6484
Mobile: 843-469-5856
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar:
http://www.google.com/calendar/embed?src=tom%40jackrussellsoftware.com&ctz=America/New_York
http://www.jackhq.com/calendar

This e-mail may contain information that is confidential, privileged or
otherwise protected from disclosure by the Health Insurance Portability and
Accountability Act (HIPAA) and other state and federal laws.  This
information is intended only for the individual names above.  Any review,
use disclosure or dissemination of this material is strictly prohibited.
If you receive this information in error, please notify CareKinesis
immediately at 888-974-2763 and delete the original at once.

**Comment by kumavis** [comment]
the readme example is missing the `menu()` definition. but no it didnt work for me when i dumped it into my app b/c of the event handlers not firing. may have been a dep versioning issue as my `package.json` would not have matched yours.

**Comment by twilson63** [comment]
got it, I will double check and get things right!  Thanks

On Thu, Feb 5, 2015 at 3:11 PM, aaron notifications@github.com wrote:

> the readme example is missing the menu() definition. but no it didnt work
> for me when i dumped it into my app b/c of the event handlers not firing.
> may have been a dep versioning issue as my package.json would not have
> matched yours.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/twilson63/mercury-router/issues/1#issuecomment-73117656
> .

## 

Tom Wilson
Jack Russell Software Company Division of CareKinesis
494 Wando Park Blvd
Mount Pleasant, SC  29464
Phone: 843-606-6484
Mobile: 843-469-5856
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar:
http://www.google.com/calendar/embed?src=tom%40jackrussellsoftware.com&ctz=America/New_York
http://www.jackhq.com/calendar

This e-mail may contain information that is confidential, privileged or
otherwise protected from disclosure by the Health Insurance Portability and
Accountability Act (HIPAA) and other state and federal laws.  This
information is intended only for the individual names above.  Any review,
use disclosure or dissemination of this material is strictly prohibited.
If you receive this information in error, please notify CareKinesis
immediately at 888-974-2763 and delete the original at once.

**Comment by twilson63** [comment]
Ok I updated the example in the readme and confirmed the example in the
example folder is working as expected, I do plan to add some tests for each
module, but it is working.

Let me know if you have any other issues!

Thank you again for taking the time to review it and I am sorry you had a
poor experience.

Thanks

Tom

On Thu, Feb 5, 2015 at 3:11 PM, aaron notifications@github.com wrote:

> the readme example is missing the menu() definition. but no it didnt work
> for me when i dumped it into my app b/c of the event handlers not firing.
> may have been a dep versioning issue as my package.json would not have
> matched yours.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/twilson63/mercury-router/issues/1#issuecomment-73117656
> .

## 

Tom Wilson
Jack Russell Software Company Division of CareKinesis
494 Wando Park Blvd
Mount Pleasant, SC  29464
Phone: 843-606-6484
Mobile: 843-469-5856
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar:
http://www.google.com/calendar/embed?src=tom%40jackrussellsoftware.com&ctz=America/New_York
http://www.jackhq.com/calendar

This e-mail may contain information that is confidential, privileged or
otherwise protected from disclosure by the Health Insurance Portability and
Accountability Act (HIPAA) and other state and federal laws.  This
information is intended only for the individual names above.  Any review,
use disclosure or dissemination of this material is strictly prohibited.
If you receive this information in error, please notify CareKinesis
immediately at 888-974-2763 and delete the original at once.

**Comment by kumavis** [comment]
cheers!
