### ISSUE TITLE
npmjs.org still points to 1.0.0

### ISSUE THREAD

**Issue by andredublin** [twilson63/mercury-router#3]
npmjs.org still points to 1.0.0 instead of 1.0.3

**Comment by twilson63** [comment]
TY,

This should be fixed now!

Tom

On Thu, Feb 5, 2015 at 12:09 PM, Andre Dublin notifications@github.com
wrote:

> npmjs.org still points to 1.0.0 instead of 1.0.3
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/twilson63/mercury-router/issues/3.

## 

Tom Wilson
Jack Russell Software Company Division of CareKinesis
494 Wando Park Blvd
Mount Pleasant, SC  29464
Phone: 843-606-6484
Mobile: 843-469-5856
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar:
http://www.google.com/calendar/embed?src=tom%40jackrussellsoftware.com&ctz=America/New_York
http://www.jackhq.com/calendar

This e-mail may contain information that is confidential, privileged or
otherwise protected from disclosure by the Health Insurance Portability and
Accountability Act (HIPAA) and other state and federal laws.  This
information is intended only for the individual names above.  Any review,
use disclosure or dissemination of this material is strictly prohibited.
If you receive this information in error, please notify CareKinesis
immediately at 888-974-2763 and delete the original at once.
