### ISSUE TITLE
Server-side

### ISSUE THREAD

**Issue by matthewp** [twilson63/mercury-router#4]
This won't work on the server-side because of the use of document.location.pathname. Not sure of what to do here.

**Comment by twilson63** [comment]
Yea, 

This solution is more to get a simple SPA app up and running, but I don't like how it embeds the event handler into the anchor element too.

Lately, I have started using:

https://github.com/visionmedia/page.js
and
https://github.com/twilson63/page-body-parser
and then just using standard anchor and form elements for the majority of my transitions and routing, the concept is still young, but it feels better and since the api's mirror express and body-parser it could serve both client and server, although it is not proven by any means so time will tell.

I hope this helps.

Thanks

Tom

**Comment by matthewp** [comment]
My ideal router would basically be this but instead of a view that defines routes I'd define routes and bind them to the global state. This way your state data remains the single source of truth, the route just updates state when using `anchor` and what not. I've actually got the basic idea working. It makes server/client exactly the same because it's all about the state, not about routes.

If you're no longer interested in maintaining this module would you consider adding me as a collaborator? I do want to break the api but would keep proper semver for users of the current api. No big deal if you want to stick with this method, I can create a new repo with my ideas.

**Comment by twilson63** [comment]
Sounds Great!   I have added you as a collaborator (github and npm), sounds exactly like where this router should go!

Thanks

Tom

**Comment by matthewp** [comment]
Awesome, thank you! I'll create a new branch and solicit feedback.
