### ISSUE TITLE
Release a tag please

### ISSUE THREAD

**Issue by kuraga** [twilson63/mercury-router#6]
Good day, @twilson63 !
Can you push your tags to github please?
There are no releases yet.
Thanks.

**Comment by twilson63** [comment]
Will do

Thx

Tom

Sent from my iPhone

On Feb 15, 2015, at 10:55 AM, Kurakin Alexander notifications@github.com
wrote:

Good day, @twilson63 https://github.com/twilson63 !
Can you push your tags to github please?
There are no releases yet?

—
Reply to this email directly or view it on GitHub
https://github.com/twilson63/mercury-router/issues/6.

**Comment by twilson63** [comment]
Done

THx

Tom

On Sun, Feb 15, 2015 at 1:01 PM, Tom Wilson tom@jackrussellsoftware.com
wrote:

> Will do
> 
> Thx
> 
> Tom
> 
> Sent from my iPhone
> 
> On Feb 15, 2015, at 10:55 AM, Kurakin Alexander notifications@github.com
> wrote:
> 
> Good day, @twilson63 https://github.com/twilson63 !
> Can you push your tags to github please?
> There are no releases yet?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/twilson63/mercury-router/issues/6.

## 

Tom Wilson
Jack Russell Software Company Division of CareKinesis
494 Wando Park Blvd
Mount Pleasant, SC  29464
Phone: 843-606-6484
Mobile: 843-469-5856
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar:
http://www.google.com/calendar/embed?src=tom%40jackrussellsoftware.com&ctz=America/New_York
http://www.jackhq.com/calendar

This e-mail may contain information that is confidential, privileged or
otherwise protected from disclosure by the Health Insurance Portability and
Accountability Act (HIPAA) and other state and federal laws.  This
information is intended only for the individual names above.  Any review,
use disclosure or dissemination of this material is strictly prohibited.
If you receive this information in error, please notify CareKinesis
immediately at 888-974-2763 and delete the original at once.

**Comment by kuraga** [comment]
Thanks
